# Service that can be used to add a plane to the planning scene.
string name
string frame_id
geometry_msgs/Pose pose
float64[3] normal
float64 offset  # In the direction of the normal
---
bool success
string message