# Service that can be used to retrieve the joints that are controlled for a given
# control type.
string control_type
---
string[] controlled_joints
string[] controlled_joints_arm
string[] controlled_joints_hand
bool success
string message