# Service that can be used to get a set of posible joint configuration for a given EE
# pose using moveit.
geometry_msgs/Pose pose
int32 attempts
---
string[] joint_names
float64[] joint_positions
bool success
string message