# Service that can be used to retrieve the joints that are currently controlled by MoveIt.
---
string[] controlled_joints
string[] controlled_joints_arm
string[] controlled_joints_hand
bool success
string message