# Service that can be used to get a valid EE pose for the robot.
BoundingRegion bounding_region
int32 attempts
---
geometry_msgs/Pose ee_pose
string[] joint_names
float64[] joint_positions
bool success
string message