# Service that can be used to control the robot hand gripper width using the panda_control_server.
# NOTE: It serves as a small wrapper around the 'franka_gripper/move` action but automatically
# sets the speed to the maximum speed. It further clips gripper width such that it is within
# the set max/min boundaries.
float64 width
bool grasping # The gripper simply moves if this is `false`.
float64 max_effort # The max effort used by the gripper.
bool wait
---
bool success
string message