actions:
- FollowJointTrajectory
authors: Rick Staa <rick.staa@outlook.com>
brief: ''
bugtracker: https://github.com/rickstaa/panda-gazebo/issues
depends:
- python3-catkin-tools
- franka_description
- catkin
- trajectory_msgs
- panda_moveit_config
- geometry_msgs
- rviz
- gazebo_msgs
- joint_trajectory_controller
- control_msgs
- moveit
- std_msgs
- message_runtime
- rospy
- actionlib
- sensor_msgs
- actionlib_msgs
- python3-catkin-pkg
- franka_gazebo
- position_controllers
- effort_controllers
- message_generation
- controller_manager_msgs
- gazebo_ros
description: A package that allows you to train several ROS based robots using Gazebo.
license: Rick Staa copyright
maintainers: Rick Staa <rick.staa@outlook.com>
msgs:
- JointLimits
- BoundingRegion
package_type: package
repo_url: https://github.com/rickstaa/panda-gazebo
srvs:
- SetJointEfforts
- GetEeRpy
- GetRandomJointPositions
- GetRandomEePose
- SetJointPositions
- AddBox
- GetEe
- GetControlledJoints
- SetGripperWidth
- AddPlane
- SetJointCommands
- GetEePose
- SetEePose
- GetMoveItControlledJoints
- GetEePoseJointConfig
- SetEe
url: https://rickstaa.dev/panda-gazebo/
