# This github action creates a new semver tag if a pull request is merged with specific
# labels.
name: Auto semver CI
on:
  push:
    branches:
      - noetic
  pull_request:
    types:
      - labeled
jobs:
  autotag:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GA_SUB }} # NOTE: Ensures that this action triggers a new workflow
      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1
  autotag-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
