name: Docs
on:
  # push:
  #   tags:
  #     - v*.*.*
  # workflow_dispatch:
  pull_request:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
        - name: Prepare
          run: |
            mkdir -p ${{github.workspace}}/src  
            mkdir -p ${{github.workspace}}/devel     
    
        - uses: docker/setup-buildx-action@v2
    
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: src
            submodules: true
    
        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            tags: panda_gazebo:noetic
            file: .ci/Dockerfile.noetic
            push: false
            load: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
      
        - name: Compile ROS package with Catkin Tools
          uses: addnab/docker-run-action@v3
          with:
            image:    panda_gazebo:noetic
            options:  -v ${{github.workspace}}/src:/src/ -v ${{github.workspace}}/devel:/devel/
            run: | # Double check if dockerfile contained all the necessary dependencies
                apt-get update
                rosdep install --from-paths /src --ignore-src --rosdistro noetic -y
                catkin config --init --extend /opt/ros/noetic
                catkin build --interleave-output --verbose

        - name: Install rosdoc_lite
          run: |
            sudo apt-get update
            sudo apt-get install -y ros-noetic-rosdoc-lite

        - uses: actions/setup-python@v4
        - name: Install documentation build dependencies
          run: |
            pip install -r panda_gazebo/requirements/doc_requirements.txt

        - name: Build the documentation
          run: |
            rosdoc_lite ../src/panda_gazebo

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: panda_gazebo/docs/build/
            force_orphan: true
