# Runs tests after a pull request is merged.
name: Panda-gazebo
on:
  push:
    branches:
      - noetic
    tags-ignore:
      - v*.*.*
jobs:
  markdown-lint: # Lints the markdown code
    name: runner / remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check markdown code quality using remark-lint
        uses: reviewdog/action-remark-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
  black: # Check python code format
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-black@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
  flake8: # Lints python code
    name: runner / flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GA_SUB }}
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Cache python environment
        uses: actions/cache@v2
        id: cache-python-env
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install the panda_gazebo package with its dependencies
        if: steps.cache-python-env.outputs.cache-hit != 'true'
        run: |
          pip install -e .[dev]
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
