# Github action that uses the 'release-please' tool to update the version, changelog 
# and create new releases.
name: Panda Gazebo release
on:
  push:
    branches:
      - noetic

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/release-please-action@optional_pyproject_toml
        with:
          token: ${{ secrets.GA_PUBLIC_PAT }}
          command: manifest
