name: ROS Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ROS-test:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        tags: ros-test:latest
        file: .ci/Dockerfile.noetic
        push: false
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build ROS package
      uses: addnab/docker-run-action@v3
      with:
        image: ros-test:latest
        shell: bash
        run: |
          . /opt/ros/noetic/setup.bash
          catkin build
